-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 13:41:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vendajogos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vendajogos` ;

-- -----------------------------------------------------
-- Schema vendajogos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendajogos` ;
USE `vendajogos` ;

-- -----------------------------------------------------
-- Table `vendajogos`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendajogos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `vendajogos`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `enderececo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendajogos`.`jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendajogos`.`jogo` ;

CREATE TABLE IF NOT EXISTS `vendajogos`.`jogo` (
  `idjogo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `dataLancamento` VARCHAR(45) NOT NULL,
  `classificacaoIndicativa` INT NOT NULL,
  `imagem` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idjogo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendajogos`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendajogos`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `vendajogos`.`carrinho` (
  `usuario_id` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  `valorTotal` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`usuario_id`, `jogo_idjogo`),
  INDEX `fk_usuario_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_usuario_has_jogo_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_jogo_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `vendajogos`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `vendajogos`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
